import { pgTable, uuid, text, timestamp, integer, jsonb, uniqueIndex, index, check } from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';
import { users } from './users';
import { clientInstallations } from './installations';
import { contentReleases } from './content';

export const playthroughAttempts = pgTable(
  'playthrough_attempts',
  {
    id: uuid('id').primaryKey().default(sql`gen_random_uuid()`),
    userId: uuid('user_id').references(() => users.id, { onDelete: 'set null' }),
    installationId: uuid('installation_id').references(() => clientInstallations.id, { onDelete: 'set null' }),
    releaseId: text('release_id').notNull().references(() => contentReleases.releaseId, { onDelete: 'restrict' }),
    chapterId: text('chapter_id').notNull(),
    attemptNumber: integer('attempt_number').notNull().default(1),
    status: text('status').notNull().default('in_progress'), // 'in_progress', 'completed', 'abandoned'
    startedAt: timestamp('started_at', { withTimezone: true }).notNull().defaultNow(),
    completedAt: timestamp('completed_at', { withTimezone: true }),
    scoreMastery: integer('score_mastery').notNull().default(0),
    outcomeTags: jsonb('outcome_tags').$type<string[]>().notNull().default([]),
  },
  (table) => [
    index('idx_attempts_user_chapter').on(table.userId, table.chapterId),
    index('idx_attempts_status').on(table.status),
    check('chk_attempts_score_non_negative', sql`${table.scoreMastery} >= 0`),
  ]
);

export const gameplayActions = pgTable(
  'gameplay_actions',
  {
    id: uuid('id').primaryKey().default(sql`gen_random_uuid()`),
    attemptId: uuid('attempt_id').notNull().references(() => playthroughAttempts.id, { onDelete: 'cascade' }),
    installationId: uuid('installation_id').references(() => clientInstallations.id, { onDelete: 'set null' }),
    actionId: uuid('action_id').notNull().unique(), // UUID v4 generated by client outbox
    clientSequence: integer('client_sequence').notNull(),
    sceneNodeId: text('scene_node_id').notNull(),
    choiceId: text('choice_id').notNull(),
    actionPayload: jsonb('action_payload').$type<Record<string, unknown>>().notNull().default({}),
    occurredAt: timestamp('occurred_at', { withTimezone: true }).notNull(),
    syncedAt: timestamp('synced_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    uniqueIndex('uq_gameplay_attempt_node').on(table.attemptId, table.sceneNodeId),
    index('idx_gameplay_actions_seq').on(table.installationId, table.clientSequence),
  ]
);

export const rewardLedger = pgTable(
  'reward_ledger',
  {
    id: uuid('id').primaryKey().default(sql`gen_random_uuid()`),
    userId: uuid('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
    releaseId: text('release_id').notNull().references(() => contentReleases.releaseId, { onDelete: 'restrict' }),
    sourceNodeId: text('source_node_id').notNull(),
    attemptId: uuid('attempt_id').references(() => playthroughAttempts.id, { onDelete: 'set null' }),
    rewardType: text('reward_type').notNull(), // 'xp', 'star', 'achievement_badge'
    amount: integer('amount').notNull().default(0),
    reason: text('reason').notNull().default('Mastery check completed'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    uniqueIndex('uq_reward_ledger_source').on(table.userId, table.releaseId, table.sourceNodeId, table.rewardType),
    index('idx_reward_ledger_user').on(table.userId),
    check('chk_reward_amount_non_negative', sql`${table.amount} >= 0`),
  ]
);
